name: deploy-client

on:
  push:
    branches:
      - master # whenever merge request to master branch
    paths:
      - "client/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #checkout repo
      - run: cd client && docker build -t karanveersinghdocker/client . # change to client service and build image
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD # login credentials
        env:
          $DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # from github secret
          $DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # from github secret
      - run: docker push karanveersinghdocker/client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save TicketMaster
      - run: kubectl rollout restart deployment client-depl # use latest version of client image
