name: deploy-auth

on:
  push:
    branches:
      - master # whenever merge request to master branch
    paths:
      - "auth/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #checkout repo
      - run: cd auth && docker build -t karanveersinghdocker/auth . # change to auth service and build image
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD # login credentials
        env:
          $DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # from github secret
          $DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # from github secret
      - run: docker push karanveersinghdocker/auth
