name: deploy-manifests

on:
  push:
    branches:
      - master # whenever merge request to master branch
    paths:
      - "infra/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #checkout repo
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save TicketMaster
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod # apply all config to cluster
